weekday:
    family: Linux Biolinum G
    size: 60
    color: '#333333'
    weight: 400
number:
    family: Laila
    size: 80
    color: '#333333'
    weight: 600
month:
    family: Lobster
    size: 150
    color: yellow
    stroke: black
    strokewidth: 0.7
shadow:
    color: white
    opacity: 0.4
holiday:
    color: '#ba3333'
weekend:
    color: '#ba4433'
ghost: 0.4
weekdays: [Пн, Вт, Ср, Чт, Пт, Сб, Вс]
months: [Январь, Февраль, Март, Апрель, Май, Июнь, Июль, Август, Сентябрь, Октябрь, Ноябрь, Декабрь]
holidays:
    2021:
        1: [1,2,3,4,5,6,7,8,9,10]
        2: [22,23]
        3: [8]
        5: [1,2,3,8,9,10]
        6: [14]
        11: [4,5]
notweekend:
    2021:
        2: [20]

