# Album
# size: { width: 297, height: 210 } # mm

# Portrait
size: { width: 210, height: 297 } # mm

extend: 6 # mm

#grid: { x: 14, y: 18 }

layout: square
# monthname: "August"
# monthnamepos: { x: 105, y: 30 }
holidays: []
notweekend: []
shortdays: []
background: "#333377"

colorstyle:
  weekday:
    family: Herculanum
    size: 30
    weight: ""
    color: "#efefef"
    stroke: ""
    strokewidth: ""
  number:
    family: Herculanum
    size: 80
    weight: ""
    color: "#efefef"
    stroke: ""
    strokewidth: ""
  month:
    family: Herculanum
    size: 80
    weight: ""
    color: white
    stroke: ""
    strokewidth: ""
  shadow:
    opacity: 0.1
    color: grey
  holiday:
    opacity: 1
    color: "#efefef"
  weekend:
    opacity: 1
    color: "#ffaaaa"
  shortday:
    opacity: 1
    color: "#fefefe"
  ghost: 0.2

weekdaynames: [mo, tu, we, th, fr, sa, su]
# weekdaynames: [1, 2, 3, 4, 5, 6, 7]
